// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package openapi

import (
	"time"
)

// Defines values for Mode.
const (
	ModeAll        Mode = "all"
	ModeBookmarked Mode = "bookmarked"
	ModeUnread     Mode = "unread"
)

// Valid indicates whether the value is a known member of the Mode enum.
func (e Mode) Valid() bool {
	switch e {
	case ModeAll:
		return true
	case ModeBookmarked:
		return true
	case ModeUnread:
		return true
	default:
		return false
	}
}

// Defines values for Order.
const (
	OrderAsc  Order = "asc"
	OrderDesc Order = "desc"
)

// Valid indicates whether the value is a known member of the Order enum.
func (e Order) Valid() bool {
	switch e {
	case OrderAsc:
		return true
	case OrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for Sort.
const (
	SortCategory    Sort = "category"
	SortPublishedAt Sort = "published_at"
	SortPublisher   Sort = "publisher"
	SortTitle       Sort = "title"
)

// Valid indicates whether the value is a known member of the Sort enum.
func (e Sort) Valid() bool {
	switch e {
	case SortCategory:
		return true
	case SortPublishedAt:
		return true
	case SortPublisher:
		return true
	case SortTitle:
		return true
	default:
		return false
	}
}

// AddFeedRequest defines model for AddFeedRequest.
type AddFeedRequest struct {
	FeedURL string `json:"feed_url"`
}

// Article defines model for Article.
type Article struct {
	Bookmarked   bool      `json:"bookmarked"`
	Category     string    `json:"category"`
	Content      string    `json:"content"`
	FeedID       int64     `json:"feed_id"`
	FeedURL      string    `json:"feed_url"`
	FetchedAt    time.Time `json:"fetched_at"`
	ID           int64     `json:"id"`
	PublishedAt  time.Time `json:"published_at"`
	Publisher    string    `json:"publisher"`
	Read         bool      `json:"read"`
	Summary      string    `json:"summary"`
	ThumbnailURL string    `json:"thumbnail_url"`
	Title        string    `json:"title"`
	URL          string    `json:"url"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Feed defines model for Feed.
type Feed struct {
	CreatedAt   time.Time  `json:"created_at"`
	FeedURL     string     `json:"feed_url"`
	ID          int64      `json:"id"`
	LastFetched *time.Time `json:"last_fetched"`
	Title       string     `json:"title"`
}

// FetchResult defines model for FetchResult.
type FetchResult struct {
	Errors  int `json:"errors"`
	Saved   int `json:"saved"`
	Skipped int `json:"skipped"`
}

// Mode 記事の絞り込みモード
type Mode string

// Order ソート順
type Order string

// PagedArticles defines model for PagedArticles.
type PagedArticles struct {
	Articles []Article `json:"articles"`
	Page     int       `json:"page"`
	PerPage  int       `json:"per_page"`
	Total    int64     `json:"total"`
}

// Sort ソート対象フィールド
type Sort string

// Category defines model for Category.
type Category = string

// Page defines model for Page.
type Page = int

// PerPage defines model for PerPage.
type PerPage = int

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// GatewayTimeout defines model for GatewayTimeout.
type GatewayTimeout = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListArticlesParams defines parameters for ListArticles.
type ListArticlesParams struct {
	// Mode 記事の絞り込みモード
	Mode *Mode `form:"mode,omitempty" json:"mode,omitempty"`

	// Category カテゴリで絞り込む
	Category *Category `form:"category,omitempty" json:"category,omitempty"`

	// Sort ソート対象フィールド
	Sort *Sort `form:"sort,omitempty" json:"sort,omitempty"`

	// Order ソート順
	Order *Order `form:"order,omitempty" json:"order,omitempty"`

	// Page ページ番号（1 始まり）
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PerPage 1 ページあたりの件数
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// SearchArticlesParams defines parameters for SearchArticles.
type SearchArticlesParams struct {
	// Q 検索キーワード
	Q string `form:"q" json:"q"`

	// Bookmarked true の場合お気に入りのみに絞り込む
	Bookmarked *bool `form:"bookmarked,omitempty" json:"bookmarked,omitempty"`

	// Category カテゴリで絞り込む
	Category *Category `form:"category,omitempty" json:"category,omitempty"`

	// Sort ソート対象フィールド
	Sort *Sort `form:"sort,omitempty" json:"sort,omitempty"`

	// Order ソート順
	Order *Order `form:"order,omitempty" json:"order,omitempty"`

	// Page ページ番号（1 始まり）
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PerPage 1 ページあたりの件数
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// AddFeedJSONRequestBody defines body for AddFeed for application/json ContentType.
type AddFeedJSONRequestBody = AddFeedRequest
