/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 記事一覧 */
        get: operations["listArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** キーワード全文検索 */
        get: operations["searchArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{id}/bookmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 記事のお気に入りをトグル
         * @description お気に入り状態を反転させ、audit_log に記録する。
         */
        post: operations["toggleBookmark"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登録済み全フィードを取得して DB に保存
         * @description CLI の `rss-feeder fetch` と同じ処理（`FetchUsecase.ExecuteAll`）を呼び出す。
         */
        post: operations["fetchLatestArticles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 登録済みフィード一覧 */
        get: operations["listFeeds"];
        put?: never;
        /** フィードを追加 */
        post: operations["addFeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * フィードを削除
         * @description 指定 ID のフィードを削除する。関連記事も連動削除される。
         */
        delete: operations["removeFeed"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 設定済みカテゴリの一覧
         * @description 記事に付与済みのカテゴリを重複なく返す（DISTINCT）。
         */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 記事の絞り込みモード
         * @default all
         * @enum {string}
         */
        Mode: "all" | "unread" | "bookmarked";
        /**
         * @description ソート対象フィールド
         * @default published_at
         * @enum {string}
         */
        Sort: "title" | "publisher" | "category" | "published_at";
        /**
         * @description ソート順
         * @default desc
         * @enum {string}
         */
        Order: "asc" | "desc";
        Article: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            feed_id: number;
            feed_url: string;
            url: string;
            title: string;
            content: string;
            /** Format: date-time */
            published_at: string;
            read: boolean;
            bookmarked: boolean;
            /** Format: date-time */
            fetched_at: string;
            publisher: string;
            thumbnail_url: string;
            summary: string;
            category: string;
        };
        Feed: {
            /** Format: int64 */
            id: number;
            feed_url: string;
            title: string;
            /** Format: date-time */
            last_fetched: string | null;
            /** Format: date-time */
            created_at: string;
        };
        AddFeedRequest: {
            feed_url: string;
        };
        PagedArticles: {
            articles: components["schemas"]["Article"][];
            /** Format: int64 */
            total: number;
            page: number;
            per_page: number;
        };
        FetchResult: {
            saved: number;
            skipped: number;
            errors: number;
        };
        Error: {
            error: string;
        };
    };
    responses: {
        /** @description リクエストパラメータが不正 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 対象が見つからない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 対象が既に存在する */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description サーバー内部エラー */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description フィードURLの探索がタイムアウトした */
        GatewayTimeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description 記事の絞り込みモード */
        Mode: components["schemas"]["Mode"];
        /** @description カテゴリで絞り込む */
        Category: string;
        /** @description ソート対象フィールド */
        Sort: components["schemas"]["Sort"];
        /** @description ソート順 */
        Order: components["schemas"]["Order"];
        /** @description ページ番号（1 始まり） */
        Page: number;
        /** @description 1 ページあたりの件数 */
        PerPage: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listArticles: {
        parameters: {
            query?: {
                /** @description 記事の絞り込みモード */
                mode?: components["parameters"]["Mode"];
                /** @description カテゴリで絞り込む */
                category?: components["parameters"]["Category"];
                /** @description ソート対象フィールド */
                sort?: components["parameters"]["Sort"];
                /** @description ソート順 */
                order?: components["parameters"]["Order"];
                /** @description ページ番号（1 始まり） */
                page?: components["parameters"]["Page"];
                /** @description 1 ページあたりの件数 */
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 記事一覧（ページネーション付き） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedArticles"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    searchArticles: {
        parameters: {
            query: {
                /** @description 検索キーワード */
                q: string;
                /** @description true の場合お気に入りのみに絞り込む */
                bookmarked?: boolean;
                /** @description カテゴリで絞り込む */
                category?: components["parameters"]["Category"];
                /** @description ソート対象フィールド */
                sort?: components["parameters"]["Sort"];
                /** @description ソート順 */
                order?: components["parameters"]["Order"];
                /** @description ページ番号（1 始まり） */
                page?: components["parameters"]["Page"];
                /** @description 1 ページあたりの件数 */
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 検索結果（ページネーション付き） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedArticles"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    toggleBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 記事 ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description トグル後の記事 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Article"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    fetchLatestArticles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得結果（件数集計） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchResult"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    listFeeds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description フィード一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"][];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    addFeed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddFeedRequest"];
            };
        };
        responses: {
            /** @description 追加されたフィード */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
            504: components["responses"]["GatewayTimeout"];
        };
    };
    removeFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description フィード ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除成功（ボディなし） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description カテゴリ名の一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
}
