name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: |
          go build -o bin/rss-feeder ./cmd/rss-feeder
          go build -o bin/web        ./cmd/web

      - name: Build rss-agent
        env:
          GOMAXPROCS: 1
          GOFLAGS: -gcflags=all=-l=0
        run: go build -p 1 -o bin/rss-agent ./cmd/agent

      - name: Test
        run: go test ./...
